# Generated by Django 2.2.1 on 2020-12-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Song Name')),
                ('artist', models.CharField(max_length=120, verbose_name='Artist')),
                ('chords', models.CharField(max_length=12, verbose_name='Chords')),
            ],
        ),
    ]
